mysql_db:
    image: mysql:5.5.48
    environment:
        - MYSQL_ROOT_PASSWORD=password
    volumes:
        - ./db/data:/var/lib/mysql
phpfpm_db:
    image: phpfpm:with_mysql 
    links: 
        - mysql_db:mysql_db
    volumes:
        - ./web/webcode:/webcode 
nginx_server:
    image: nginx:1.8
    links: 
        - phpfpm_db:phpfpm_db
    volumes:
        - ./server/conf/default_server.conf:/etc/nginx/conf.d/default.conf 
    volumes_from:
        - phpfpm_db
    ports:
        - "80:80"
